var teams_start = [
  {
    id: 1,
    name: "Globuli Bianchi",
    round_persi: 0,
    round_vinti: 0,
    backgroundColor: "rgb(255, 255, 0)",
    borderColor: "rgb(255, 255, 0)",
    lineup: [
      { id: 101, livello: 1, firstname: "", lastname: "FERRETTI" },
      { id: 102, livello: 1, firstname: "", lastname: "PECORARI" },
      { id: 103, livello: 2, firstname: "", lastname: "PLACIDO" },
      { id: 104, livello: 2, firstname: "", lastname: "CANDELA" },
      { id: 105, livello: 3, firstname: "", lastname: "CARCHESIO" },
      { id: 106, livello: 3, firstname: "", lastname: "GIAMPIETRO" },
      { id: 107, livello: 4, firstname: "", lastname: "FENAROLI" },
      { id: 108, livello: 4, firstname: "", lastname: "GUALTIERI" },
      { id: 109, livello: 5, firstname: "", lastname: "GASBARRO" },
      { id: 110, livello: 5, firstname: "", lastname: "ARDITO" },
      { id: 111, livello: 6, firstname: "", lastname: "DELL'ISOLA" },
      { id: 112, livello: 6, firstname: "", lastname: "SASCIA" },
    ],
  },
  {
    id: 2,
    name: "Globuli Rossi",
    round_persi: 0,
    round_vinti: 0,
    backgroundColor: "rgb(255, 0, 0)",
    borderColor: "rgb(255, 0, 0)",
    lineup: [
      { id: 201, livello: 1, firstname: "", lastname: "TRACANNA" },
      { id: 202, livello: 1, firstname: "", lastname: "SCIOLI" },
      { id: 203, livello: 2, firstname: "M.", lastname: "RICCI" },
      { id: 204, livello: 2, firstname: "M.", lastname: "DE ANGELIS" },
      { id: 205, livello: 3, firstname: "", lastname: "DI STEFANO" },
      { id: 206, livello: 3, firstname: "", lastname: "RENZETTI" },
      { id: 207, livello: 4, firstname: "", lastname: "VENDITTI" },
      { id: 208, livello: 4, firstname: "", lastname: "SANTUCCIONE" },
      { id: 209, livello: 5, firstname: "", lastname: "BALLONE" },
      { id: 210, livello: 5, firstname: "", lastname: "DI FEBO" },
      { id: 211, livello: 6, firstname: "", lastname: "BORRELLI" },
      { id: 212, livello: 6, firstname: "", lastname: "PASQUARELLI" },
    ],
  },
  {
    id: 3,
    name: "Fattore RH",
    round_persi: 0,
    round_vinti: 0,
    backgroundColor: "rgb(0, 0, 255)",
    borderColor: "rgb(0, 0, 255)",
    lineup: [
      { id: 301, livello: 1, firstname: "", lastname: "DI BIASE" },
      { id: 302, livello: 1, firstname: "", lastname: "ASSETTA" },
      { id: 303, livello: 2, firstname: "", lastname: "MORELLI" },
      { id: 304, livello: 2, firstname: "", lastname: "D'ANGELO" },
      { id: 305, livello: 3, firstname: "", lastname: "MARZOCCHI" },
      { id: 306, livello: 3, firstname: "", lastname: "DE COLLIBUS" },
      { id: 307, livello: 4, firstname: "", lastname: "CONSORTE" },
      { id: 308, livello: 4, firstname: "", lastname: "FANFONI" },
      { id: 309, livello: 5, firstname: "", lastname: "RANALLI" },
      { id: 310, livello: 5, firstname: "", lastname: "MARINI" },
      { id: 311, livello: 6, firstname: "", lastname: "TRAVAGLINI" },
      { id: 312, livello: 6, firstname: "", lastname: "DONNARUMMA" },
    ],
  },
  {
    id: 4,
    name: "Piastrine",
    round_persi: 0,
    round_vinti: 0,
    backgroundColor: "rgb(0, 255, 0)",
    borderColor: "rgb(0, 255, 0)",
    lineup: [
      { id: 401, livello: 1, firstname: "", lastname: "DI LAURO" },
      { id: 402, livello: 1, firstname: "", lastname: "DE GRANDIS" },
      { id: 403, livello: 2, firstname: "", lastname: "LOPANE" },
      { id: 404, livello: 2, firstname: "", lastname: "NICCOLO'" },
      { id: 405, livello: 3, firstname: "", lastname: "TROIANI" },
      { id: 406, livello: 3, firstname: "", lastname: "DELLA PENNA" },
      { id: 407, livello: 4, firstname: "", lastname: "CICCONE" },
      { id: 408, livello: 4, firstname: "", lastname: "VERNA" },
      { id: 409, livello: 5, firstname: "", lastname: "D'ETTORRE" },
      { id: 410, livello: 5, firstname: "", lastname: "CANACCI" },
      { id: 411, livello: 6, firstname: "", lastname: "CARLESI" },
      { id: 412, livello: 6, firstname: "", lastname: "DI BERARDINO" },
      { id: 413, livello: 4, firstname: "", lastname: "D'ANGELO" },
    ],
  },
];
